/**
 * 每任务工作目录模型的判定与落盘（从 daemon/index.ts 抽出以便单测）。
 *
 * 为什么单独一个文件：daemon/index.ts 顶层 `requireParentPort()` 在非 utilityProcess
 * 环境 import 即抛，无法直接单测（conversation-search.ts / prompt-preview.ts /
 * context-usage-detail.ts 是同一抽法）。这里承载「分配 / 归属判定 / 转正 / reveal 校验」
 * 四类规则，供 daemon 接线调用与单测共用同一份实现。
 *
 * 模型（spec: align-per-task-dirs，对齐 WorkBuddy 的 isPlayground 模型）：
 *   - 未选工作空间的新任务，cwd 先记为**待分配**（`""`），首次执行（真正建宿主）时才在
 *     生效根下分配 `<YYYY-MM-DD-HH-mm-ss>` 独立目录；
 *   - 任务区归属只看 cwd 形态，不比对当前生效根；
 *   - 转正 = 把该任务的自动目录整体 rename 成空间名。
 */

import { existsSync, mkdirSync, renameSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { isAutoSessionDirName } from "../shared/workspace.ts";
import { createSessionDir } from "../core/workspace.ts";
import { isWorktreePath } from "../core/worktree.ts";

/**
 * 历史共享临时目录的目录名（`<生效根>/临时任务`）。
 * 新任务不再落这里（退出落点），但它仍是任务区的一种形态 —— 存量会话原地保留、
 * 继续归任务区，所以判定与转正都还要认这个名字。
 */
export const LEGACY_TEMP_TASKS_DIR_NAME = "临时任务";

/**
 * 该 cwd 是否是「任务私有 / 共享的任务目录」而非用户经营的工作空间：
 *   - 自动分配目录（`<任意根>/YYYY-MM-DD-HH-mm-ss`）；
 *   - 历史共享临时目录（`<任意根>/临时任务`）；
 *   - 旧 playground 占位目录（配置目录下的技术 cwd）。
 *
 * 与 isTaskCwd 的区别：这里**不含**生效根本身与待分配空串。生效根是用户显式选过的
 * 默认工作空间，resume 后应继续作为新任务落点；而任务私有目录不是 —— 见各调用点。
 */
export function isTaskPrivateCwd(cwd: string, configDir: string): boolean {
	const name = basename(cwd);
	return (
		isAutoSessionDirName(name) ||
		name === LEGACY_TEMP_TASKS_DIR_NAME ||
		cwd === join(configDir, "playground") ||
		/*
		 * worktree 副本（对齐清单 C22 / L27）：启用副本的会话 cwd 指向
		 * `<配置目录>/worktrees/<仓库名>/<分支 id>`。归任务区有两个理由：
		 *   ① 它不是用户经营的工作空间，进空间区会以 `main-a1b2c3d4` 这种目录名成组；
		 *   ② 更要紧的是 isOwnedSessionDir 因此为假 —— 「保存到工作空间」走**新建目录**的
		 *      回退分支，而不会去 rename 副本目录。rename 一份 git worktree 会让仓库里的
		 *      worktree 登记表（.git/worktrees/）指向一个不存在的路径，仓库从此半坏。
		 */
		isWorktreePath(cwd)
	);
}

/**
 * 该 cwd 是否归「任务」区。任一命中即真：
 *   - `""` 待分配（新建任务尚未首次执行，对齐 WorkBuddy `isPlayground → cwd=""`）；
 *   - 自动分配目录；
 *   - 历史共享临时目录；
 *   - 旧 playground 占位目录。
 *
 * **不含「生效根本身」**（2026-09-15 起，口径对齐 WorkBuddy）：cwd = 根本身归**空间区**成组。
 * WorkBuddy 的分组条件是可证的：`!isPlayground && cwd && isAbsolute(cwd)` 即按 cwd
 * 成组（`docs/WorkBuddy-reference/extracted/renderer/assets/ui-docs-viewer-C2jT2eXi.js:
 * 205329-205347`），root 作为 cwd 既非 playground 也不为空，因此进「空间」。
 *
 * 【2026-09-15 订正】上句原写「cwd = 根本身只可能来自用户显式选 picker 里的『默认工作空间』」
 * —— 那个固定项已删（WorkBuddy 的 picker 选项全部来自 `wb.workspaces.list()`，没有指向根的
 * 固定项）。现在该状态只可能来自「打开本地文件夹…」或旧会话，但**判定不变**：根仍然不是
 * 任务区，理由从「用户刻意选过它」变成「它不是任务私有形态（非空、非自动目录、非临时目录）」。
 *
 * 旧模型下「未选工作空间 = 临时任务」的 cwd 就落在根本身，两者同义，才顺手把根也划进
 * 任务区；新模型（spec: align-per-task-dirs）改走「待分配 → 首次执行分配时间戳目录」，
 * cwd 不再是根本身，该前提已消失。**别改回任务区**：cwd = 根的历史会话会整体跳回任务区，
 * 而它本该作为空间在侧栏成组。
 *
 * **只看形态、不比对生效根**（这是另一处要修的漂移）：用户改了「默认存储路径」后，
 * 旧任务目录（cwd 仍在原根下）依旧命中，不会因为根变了就被误判成空间组。
 * 历史上用「当前生效根」比对时，改一次根旧任务就整体漂到空间区。
 */
export function isTaskCwd(cwd: string, configDir: string): boolean {
	return cwd === "" || isTaskPrivateCwd(cwd, configDir);
}

/**
 * 该 cwd 是否是「本会话独占、可整体 rename」的自动目录。
 * 历史共享临时目录绝不可 rename（别的老任务也在里面，改名会带走别人的产物），
 * 旧 playground 占位目录同理；它们走 promoteSessionDir 的回退分支。
 */
export function isOwnedSessionDir(cwd: string): boolean {
	const name = basename(cwd);
	return isAutoSessionDirName(name) && name !== LEGACY_TEMP_TASKS_DIR_NAME;
}

/**
 * 该目录可否作为工作空间选择器的候选（workspaceSnapshot 列表的过滤谓词）。
 *
 * 排除两类「不是用户经营的工作空间、只是恰好躺在根下」的目录：
 *   - 每任务自动分配目录（`YYYY-MM-DD-HH-mm-ss`）：这是某个任务的私有目录，
 *     切进去等于和另一个任务共用 cwd；
 *   - 历史共享临时目录 `临时任务`：属于任务区，同样不是可切换的空间。
 * 不排除「生效根本身」：它在快照里是独立的 defaultRoot 字段，不在候选列表里。
 *
 * WorkBuddy 同款做法：picker 用 `isManualWorkspaceCwd` 把 `isAutoGeneratedWorkspaceCwd`
 * 形态的目录挡在候选之外（docs/WorkBuddy/_analysis/extracted/renderer/assets/
 * ui-docs-viewer-C2jT2eXi.js:113850-113856）。
 *
 * 注意别与 isTaskPrivateCwd 合并：那是**任务区归属**口径（还认旧 playground 占位目录），
 * 这里是**选择器候选**口径，两者会随需求各自演化。
 */
export function isSelectableWorkspaceDir(dir: string): boolean {
	const name = basename(dir);
	return !isAutoSessionDirName(name) && name !== LEGACY_TEMP_TASKS_DIR_NAME;
}

/**
 * 待分配（`""`）→ 在生效根下分配独立时间戳目录；其余形态原样返回、不落盘。
 *
 * 首次执行（真正建宿主）时才调用：新建任务本身不建目录 —— 用户可能点了「新建任务」
 * 却没发消息就切走，那一刻不该留下空目录（spec: align-per-task-dirs，比 WorkBuddy
 * 的「创建即建目录」更干净）。
 * `now` 仅用于单测确定性，不传走真实时钟。
 */
export function allocatePendingCwd(cwd: string, root: string, now?: Date): string {
	return cwd === "" ? createSessionDir(root, now) : cwd;
}

/**
 * 转正落盘：把任务目录改名 / 另建为目标空间目录（调用方保证会话宿主此刻已 dispose）。
 *
 * rename 分支（本会话独占的自动目录）：同根整体改名，产物与 `<cwd>/.kamibuddy/` 记忆
 *   随目录一起走 —— 这是对 WorkBuddy 的改良（它只加显示名、目录仍叫时间戳，时间戳
 *   目录会永久堆积）。跨卷（用户改过默认存储路径，旧目录在新根的另一盘）时 rename
 *   会抛 EXDEV，由调用方响亮报错并恢复宿主。
 * 回退分支（历史共享临时目录里的老会话、生效根本身、别的形态）：**绝不能 rename** ——
 *   共享目录归属多个老任务，改名会带走别人的产物。退回旧的「新建命名目录 + 切 cwd」，
 *   老目录原地保留（spec：历史目录不迁移、不删除）。
 *
 * 目标已存在即拒：静默复用会把本任务产物混进别人的目录里。调用方在 dispose 之前还会
 * 再查一次（早拒、且那时主机毫发无损），这里是 rename 前的兜底（挡校验与改名之间的竞态）。
 */
export function promoteSessionDir(cwd: string, target: string): void {
	if (existsSync(target)) throw new Error(`目标目录已存在：${target}`);
	if (isOwnedSessionDir(cwd)) {
		renameSync(cwd, target);
		return;
	}
	mkdirSync(target, { recursive: true });
}

/**
 * reveal 校验：目标必须是「已知工作空间」或「任一已知会话的 cwd」。
 *
 * 放宽（原只认前者）的理由：任务区会话不成组（listWorkspaceGroups 只收非临时会话的
 * cwd），它的时间戳目录不在组里 —— 不放宽则用户在任务行点「打开文件夹」打不开自己
 * 的产物目录。放宽不等于放开：未知路径（用户家目录、系统目录）不在 known 里，仍一律拒
 * —— 否则任意网页/XSS 都能借 main 的 shell.openPath 打开任意路径。
 */
export function isRevealableCwd(cwd: string, knownCwds: readonly string[]): boolean {
	const target = resolve(cwd);
	return knownCwds.some((known) => resolve(known) === target);
}
